### ISSUE TITLE
The UI fails to load 

### ISSUE THREAD

**Issue by parulnith** [microsoft/adatest#9]
Adatest looks like a promising library and has piqued my interest since I'm researching Model Debugging methods for Deep learning systems. I ran the notebooks provided in the `Notebooks` folder, however, the UI fails to load and throws the following  error

`FileNotFoundError: [Errno 2] No such file or directory: '/home/paperspace/.local/lib/python3.8/site-packages/adatest/../client/dist/main.js'`

Any pointers on resolving the error? Thanks

**Comment by Harsha-Nori** [comment]
Hi @parulnith, 

Thanks for reporting this! We've merged a fix for this (https://github.com/microsoft/adatest/pull/8) and will do a new PyPI release soon which will address this -- happy to update this thread once the fix is out.

In the meanwhile, another installation option is to clone the repository with:

`git clone https://github.com/microsoft/adatest.git`

and do a local install with:

`python setup.py install` or `pip install .` in the newly cloned adatest/ folder. Local installs should not run into this issue. Thanks again for bringing this to our attention!

**Comment by Harsha-Nori** [comment]
Hi @parulnith, 

There's a new release out -- v0.2.3 -- that should address this issue. You can upgrade your installation with `pip install -U adatest`, and verify you have the right version with `pip show adatest`. Mind trying this out and letting us know if the upgrade fixed your issue?

**Comment by parulnith** [comment]
Thanks, @Harsha-Nori , The issue is resolved now 🙏🏻
